spring.application.name=social_media_platform_backend

spring.datasource.url=jdbc:mysql://localhost:3306/social_media_platform
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

server.port=8080